### PR TITLE
Exit if agent cannot initially create certificate or parse flags

### PR DESCRIPTION
**Pull request by dafydd-t**
currently, the agent will continue 'running' in a loop of errors if it cannot get a key signed. This gives the impression that the agent is running happily, even when it isn't, making it more difficult to detect errors.

This PR changes the behaviour so that the agent will exit if it cannot get a valid certificate or if it cannot parse the config flags given. 

With this, it will be easier to detect a misconfigured agent e.g. running as a k8s deployment (it will crashLoop)

- We still verify the keys on exit from the ssh command, so we still cover the case where a certificate expires since the last start.

### CODE REVIEW

**Comment by chit786** [comment]
+1

**Review by stephaniehingtgen — APPROVED** [review]

**Review by AustinDeric — APPROVED** [review]
+1 (great tests, ty!)

**Comment by nckswt** [comment]
@dafydd-t do we have any timeline for this rolling out? It's a critical failure for us and affecting our production stacks.

**Comment by chit786** [comment]
@dafydd-t unfortunately #31 did not fix the issue. More details provided on the grafana case. May be an idea: 
it should be pretty straightforward to provide healthcheck possibility / probe for k8s setup that way we can run multiple replicas and since each of them fails at different duration atleast we will have high availability when the pod crashes and k8s takes care of container restart.

**Comment by nckswt** [comment]
Seconding @chit786 's response, though we're just running a single instance in Docker on an EC2

**Comment by chit786** [comment]
thanks @dafydd-t for picking this up.. 💪

**Pull request merged**
